"""File containing UI configuration constants for the Streamlit app."""

BOARD_SYMBOLS = {
    "X": "❌", # Cross symbol for player X
    "O": "⭕", # Circle symbol for player O
    None: "➖" # Dash symbol for empty cells
}

ICONS = {
    "victory": "🏆",
    "draw": "🤝",
}

HUMAN_PLAYER_NAME = "You"
AI_PLAYER_NAME = "Computer"

UI_MESSAGES = {
    "page_title": "Tic Tac Toe Game",
    "page_icon": "🎮​",
    "header_title": "🎮​ Tic Tac Toe Game",
    "header_subtitle": "Play the classic Tic Tac Toe game!",
    "rules_expander": "📜 Game Rules",
    "choose_options": "Choose options in the sidebar to launch the game",
    "choose_symbol": "Choose your symbol:",
    "symbol_options": "Symbol options:",
    "symbol_info": "Symbol {} starts first.",
    "current_turn": "Current turn:",
    "draw": "It's a draw!",
    "victory": "{} wins! Symbol: {}",
    "launch": "Launch Game",
    "quick_restart": "↻ Quick Restart",
    "options_title": "⚙️ Game Options"
}

GAME_RULES = """
1. The game is played on a 3x3 grid.
2. You can choose to play as either {} or {}. The player with {} always goes first.
3. Players take turns placing their symbol in an empty cell on the grid.
4. The first player to get three of their symbols in a row (horizontally, vertically, or diagonally) wins the game.
5. If all cells are filled and no player has three in a row, the game is a draw.
6. You can restart the game at any time by clicking the "Quick Restart" after the game ends. Or you can change your symbol and launch a new game from the sidebar options.
7. Enjoy playing and have fun!
"""

CUSTOM_CSS = \
    """<style>
        /* Remove the large space between rows generated by the for loop */
        .tictactoe-board [data-testid="stVerticalBlock"] > div {
            padding-top: 0rem !important;
            padding-bottom: 0rem !important;
        }
        /* Force the TicTacToe buttons to be perfect squares */
        .tictactoe-board div.stButton > button {
            width: 5rem !important;
            height: 5rem !important;
            padding: 0rem !important;
            margin: 0rem !important;
        }

        /* Custom CSS to style the Streamlit app */
        .stMainBlockContainer {
            max-width: 150rem;
            padding-left: 2rem;
            padding-right: 2rem;
        }
    </style>"""
