"""File containing UI configuration constants for the Streamlit app."""

BOARD_SYMBOLS = {
    "X": "❌", # Cross symbol for player X
    "O": "⭕", # Circle symbol for player O
    None: "➖" # Dash symbol for empty cells
}

ICONS = {
    "victory": "🏆",
    "draw": "🤝",
}

HUMAN_PLAYER_NAME = "You"
AI_PLAYER_NAME = "Computer"

UI_MESSAGES = {
    "page_title": "Tic Tac Toe Game",
    "page_icon": "🎮​",
    "header_title": "🎮​ Tic Tac Toe Game",
    "header_subtitle": "Play the classic Tic Tac Toe game!",
    "choose_options": "Choose options in the sidebar to launch the game",
    "choose_symbol": "Choose your symbol:",
    "symbol_options": "Symbol options:",
    "symbol_info": "Symbol {} starts first.",
    "current_turn": "Current turn:",
    "draw": "It's a draw!",
    "victory": "{} wins! Symbol: {}",
    "launch": "Launch Game",
    "quick_restart": "↻ Quick Restart",
    "options_title": "⚙️ Game Options"
}

CUSTOM_CSS = \
    """<style>
        /* Remove the large space between rows generated by the for loop */
        .tictactoe-board [data-testid="stVerticalBlock"] > div {
            padding-top: 0rem !important;
            padding-bottom: 0rem !important;
        }
        /* Force the TicTacToe buttons to be perfect squares */
        .tictactoe-board div.stButton > button {
            width: 5rem !important;
            height: 5rem !important;
            padding: 0rem !important;
            margin: 0rem !important;
        }

        /* Custom CSS to style the Streamlit app */
        .stMainBlockContainer {
            max-width: 150rem;
            padding-left: 2rem;
            padding-right: 2rem;
        }
    </style>"""
